In [2]:
# Standard library imports for this phase
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
%matplotlib inline

In [6]:
import sys
import os

# This adds the parent directory (Market_basket) to the system path
# so that the 'src' folder can be found.
sys.path.append(os.path.abspath(os.path.join('..')))

# Now try the import again
from src.scraping import scrape_food_categories
print("✅ Success: src.scraping imported correctly!")

Scraper Module Loaded Successfully.
✅ Success: src.scraping imported correctly!

In [3]:
# Load the raw data from Phase 2
DATA_PATH = '../data/raw/groceries.csv'
df = pd.read_csv(DATA_PATH)

# Clean Data: Remove the duplicates identified in Phase 2
before = len(df)
df_clean = df.drop_duplicates().copy()
after = len(df_clean)

print(f"Data Cleaning: Removed {before - after} duplicate rows.")
print(f"Current Shape: {df_clean.shape}")

Data Cleaning: Removed 759 duplicate rows.
Current Shape: (38006, 3)

In [4]:
# Convert Date to datetime objects
df_clean['Date'] = pd.to_datetime(df_clean['Date'], format='%d-%m-%Y')

# Feature Engineering: Create 'Is_Weekend' (Saturday=5, Sunday=6)
df_clean['Is_Weekend'] = df_clean['Date'].dt.dayofweek.isin([5, 6])

print("Feature Engineering: Created 'Is_Weekend' column.")
df_clean.head()

Feature Engineering: Created 'Is_Weekend' column.

   Member_number       Date   itemDescription  Is_Weekend
0           1808 2015-07-21    tropical fruit       False
1           2552 2015-01-05        whole milk       False
2           2300 2015-09-19         pip fruit        True
3           1187 2015-12-12  other vegetables        True
4           3037 2015-02-01        whole milk        True

In [7]:
from src.scraping import scrape_food_categories

# 1. Get categories from Wikipedia
scraped_categories = scrape_food_categories()

# 2. Simple mapping function (You can expand this list)
def get_category(item):
    item = item.lower()
    if any(x in item for x in ['milk', 'yogurt', 'cheese', 'cream']): return 'Dairy'
    if any(x in item for x in ['veg', 'fruit', 'root', 'onion']): return 'Produce'
    if any(x in item for x in ['beer', 'wine', 'soda', 'water']): return 'Beverages'
    if any(x in item for x in ['bread', 'roll', 'bun', 'pastry']): return 'Bakery'
    if any(x in item for x in ['sausage', 'beef', 'pork', 'chicken']): return 'Meat'
    return 'Other'

# 3. Apply the integration
df_clean['Category'] = df_clean['itemDescription'].apply(get_category)

print("Data Integration: Wikipedia categories merged successfully.")

Data Integration: Wikipedia categories merged successfully.

In [8]:
# Final Formatting: Reorder for clarity
df_final = df_clean[['Member_number', 'Date', 'Is_Weekend', 'itemDescription', 'Category']]

# Save the prepared data
OUTPUT_PATH = '../data/processed/prepared_groceries.csv'
df_final.to_csv(OUTPUT_PATH, index=False)

print(f"FINAL PREPARED DATASET SUMMARY")
print(f"Shape: {df_final.shape}")
print(f"Prepared dataset saved to: {OUTPUT_PATH}")
df_final.head()

FINAL PREPARED DATASET SUMMARY
Shape: (38006, 5)
Prepared dataset saved to: ../data/processed/prepared_groceries.csv

   Member_number       Date  Is_Weekend   itemDescription Category
0           1808 2015-07-21       False    tropical fruit  Produce
1           2552 2015-01-05       False        whole milk    Dairy
2           2300 2015-09-19        True         pip fruit  Produce
3           1187 2015-12-12        True  other vegetables  Produce
4           3037 2015-02-01        True        whole milk    Dairy